import Link from "next/link";
import { FileCheck } from "lucide-react";

export const metadata = {
  title: "AI Disclaimer — DocReview AI",
  description: "Understanding the limitations of AI-powered legal document analysis.",
};

export default function DisclaimerPage() {
  return (
    <div className="min-h-screen bg-gray-50">
      <header className="bg-white border-b">
        <div className="max-w-3xl mx-auto px-4 h-16 flex items-center gap-3">
          <Link href="/" className="flex items-center gap-2 font-semibold text-lg">
            <FileCheck className="h-5 w-5 text-blue-600" />
            DocReview AI
          </Link>
          <span className="text-gray-300">/</span>
          <span className="text-sm text-gray-500">AI Disclaimer</span>
        </div>
      </header>

      <main className="max-w-3xl mx-auto px-4 py-12">
        <h1 className="text-3xl font-bold text-gray-900 mb-2">AI Disclaimer</h1>
        <p className="text-sm text-gray-500 mb-8">Last updated: July 2026</p>

        <div className="prose prose-gray max-w-none space-y-6">
          <div className="p-6 bg-red-50 border border-red-200 rounded-lg">
            <p className="text-red-800 font-bold text-lg mb-2">
              IMPORTANT: Read This Carefully
            </p>
            <p className="text-red-700">
              DocReview AI uses artificial intelligence to assist with document analysis.
              IT IS NOT A SUBSTITUTE FOR PROFESSIONAL LEGAL JUDGMENT. Always have a
              licensed attorney review any document before relying on its contents.
            </p>
          </div>

          <h2 className="text-xl font-bold text-gray-900 mt-8">
            1. No Legal Advice
          </h2>
          <p className="text-gray-700">
            DocReview AI is a technology tool designed to assist legal professionals with
            document review. It does not provide legal advice, legal opinions, or legal
            recommendations. The analyses, summaries, risk flags, and suggestions
            generated by our AI are for informational and efficiency purposes only.
          </p>

          <h2 className="text-xl font-bold text-gray-900 mt-8">
            2. No Attorney-Client Relationship
          </h2>
          <p className="text-gray-700">
            Use of DocReview AI does not create an attorney-client relationship between
            you and DocReview AI, its parent company, its employees, or its technology.
            An attorney-client relationship can only be formed through a direct,
            written agreement with a licensed attorney.
          </p>

          <h2 className="text-xl font-bold text-gray-900 mt-8">
            3. AI Limitations
          </h2>
          <p className="text-gray-700">
            You acknowledge and understand that:
          </p>
          <ul className="list-disc pl-6 space-y-2 text-gray-700">
            <li>
              Our AI may produce incomplete, inaccurate, or misleading results.
            </li>
            <li>
              The AI does not understand the specific context of your legal matter,
              jurisdiction, or client circumstances.
            </li>
            <li>
              The AI may miss nuanced legal issues, jurisdictional variations,
              or recent changes in law.
            </li>
            <li>
              The AI cannot exercise professional judgment, which is the
              responsibility of the reviewing attorney.
            </li>
            <li>
              Output quality depends on input quality — incomplete or poorly
              scanned documents may produce unreliable results.
            </li>
          </ul>

          <h2 className="text-xl font-bold text-gray-900 mt-8">
            4. Human Review Required
          </h2>
          <p className="text-gray-700">
            ALL AI-generated outputs from DocReview AI MUST be reviewed by a
            qualified, licensed attorney before being relied upon for any purpose.
            By using this service, you agree that:
          </p>
          <ul className="list-disc pl-6 space-y-2 text-gray-700">
            <li>
              You will independently verify all AI-generated analyses,
              risk assessments, and recommendations.
            </li>
            <li>
              You remain solely responsible for all legal advice provided to
              your clients.
            </li>
            <li>
              You will not represent AI-generated content as your own
              unverified legal analysis.
            </li>
          </ul>

          <h2 className="text-xl font-bold text-gray-900 mt-8">
            5. Jurisdictional Variations
          </h2>
          <p className="text-gray-700">
            Laws vary significantly by jurisdiction. DocReview AI may not account for
            state-specific, local, or international legal requirements. It is your
            responsibility to ensure compliance with all applicable laws and
            regulations in your jurisdiction.
          </p>

          <h2 className="text-xl font-bold text-gray-900 mt-8">
            6. No Warranty
          </h2>
          <p className="text-gray-700">
            DocReview AI is provided on an &quot;AS IS&quot; and &quot;AS AVAILABLE&quot; basis
            without warranties of any kind, either express or implied, including but
            not limited to warranties of merchantability, fitness for a particular
            purpose, accuracy, or non-infringement.
          </p>

          <h2 className="text-xl font-bold text-gray-900 mt-8">
            7. Limitation of Liability
          </h2>
          <p className="text-gray-700">
            To the fullest extent permitted by law, DocReview AI and its affiliates
            shall not be liable for any direct, indirect, incidental, special,
            consequential, or punitive damages arising from or related to your use
            of the service, including but not limited to damages resulting from
            reliance on AI-generated content.
          </p>

          <h2 className="text-xl font-bold text-gray-900 mt-8">
            8. Ethical Obligations
          </h2>
          <p className="text-gray-700">
            Attorneys using DocReview AI remain bound by all applicable rules of
            professional conduct. Depending on your jurisdiction, you may have
            obligations to:
          </p>
          <ul className="list-disc pl-6 space-y-2 text-gray-700">
            <li>Disclose the use of AI tools to clients.</li>
            <li>Maintain competence in the use of technology.</li>
            <li>Ensure the confidentiality of client information.</li>
            <li>Supervise AI outputs as you would supervise junior staff.</li>
          </ul>

          <h2 className="text-xl font-bold text-gray-900 mt-8">
            9. Questions
          </h2>
          <p className="text-gray-700">
            If you have questions about this disclaimer, contact us at{" "}
            <a href="mailto:legal@docreview.ai" className="text-blue-600 hover:text-blue-800 underline">
              legal@docreview.ai
            </a>.
          </p>
        </div>
      </main>

      <footer className="border-t bg-white">
        <div className="max-w-3xl mx-auto px-4 py-6 text-center text-sm text-gray-500">
          <Link href="/" className="hover:text-gray-700">Home</Link>
          {" · "}
          <Link href="/terms" className="hover:text-gray-700">Terms</Link>
          {" · "}
          <Link href="/privacy" className="hover:text-gray-700">Privacy</Link>
        </div>
      </footer>
    </div>
  );
}
