import Link from "next/link";
import { Layers } from "lucide-react";

export const metadata = {
  title: "AI Disclaimer — GlassEstimate",
  description: "Understanding the limitations of AI-assisted glass estimation.",
};

export default function DisclaimerPage() {
  return (
    <div className="min-h-screen bg-gray-50">
      <header className="bg-white border-b">
        <div className="max-w-3xl mx-auto px-4 h-16 flex items-center gap-3">
          <Link href="/" className="flex items-center gap-2 font-semibold text-lg">
            <Layers className="h-5 w-5 text-emerald-600" />
            GlassEstimate
          </Link>
          <span className="text-gray-300">/</span>
          <span className="text-sm text-gray-500">AI Disclaimer</span>
        </div>
      </header>

      <main className="max-w-3xl mx-auto px-4 py-12">
        <h1 className="text-3xl font-bold text-gray-900 mb-2">AI Disclaimer</h1>
        <p className="text-sm text-gray-500 mb-8">Last updated: August 2026</p>

        <div className="prose prose-gray max-w-none space-y-6">
          <div className="p-6 bg-red-50 border border-red-200 rounded-lg">
            <p className="text-red-800 font-bold text-lg mb-2">
              IMPORTANT: Read This Carefully
            </p>
            <p className="text-red-700">
              GlassEstimate provides AI-assisted pricing estimates for glass systems.
              IT IS NOT A SUBSTITUTE FOR PROFESSIONAL MEASUREMENT OR PRICING JUDGMENT.
              Always verify measurements on-site and confirm final pricing before presenting
              to clients.
            </p>
          </div>

          <h2 className="text-xl font-bold text-gray-900 mt-8">1. Estimation Tool, Not Professional Advice</h2>
          <p className="text-gray-700">
            GlassEstimate is a technology tool designed to assist glass professionals with
            pricing estimation and system configuration. It does not replace on-site
            measurement, professional installation knowledge, or compliance with local
            building codes. Estimates are for planning purposes only.
          </p>

          <h2 className="text-xl font-bold text-gray-900 mt-8">2. AI Limitations</h2>
          <p className="text-gray-700">You acknowledge and understand that:</p>
          <ul className="list-disc pl-6 space-y-2 text-gray-700">
            <li>Our AI may produce pricing that needs adjustment for your local market rates.</li>
            <li>The system cannot verify on-site measurements or conditions.</li>
            <li>Glass pricing varies by region, supplier, and market conditions.</li>
            <li>Hardware availability and pricing may change without notice.</li>
            <li>Cutout and hardware positions shown are guidelines — always verify against manufacturer specs.</li>
          </ul>

          <h2 className="text-xl font-bold text-gray-900 mt-8">3. Human Review Required</h2>
          <p className="text-gray-700">
            ALL estimates generated by GlassEstimate MUST be reviewed by a qualified
            glass professional before being presented to clients. By using this service,
            you agree that you remain solely responsible for final pricing, measurements,
            and installation.
          </p>

          <h2 className="text-xl font-bold text-gray-900 mt-8">4. No Warranty</h2>
          <p className="text-gray-700">
            GlassEstimate is provided on an &quot;AS IS&quot; and &quot;AS AVAILABLE&quot; basis
            without warranties of any kind, either express or implied.
          </p>

          <h2 className="text-xl font-bold text-gray-900 mt-8">5. Limitation of Liability</h2>
          <p className="text-gray-700">
            To the fullest extent permitted by law, GlassEstimate and its affiliates
            shall not be liable for any direct, indirect, incidental, special,
            consequential, or punitive damages arising from your use of the service.
          </p>
        </div>
      </main>

      <footer className="border-t bg-white">
        <div className="max-w-3xl mx-auto px-4 py-6 text-center text-sm text-gray-500">
          <Link href="/" className="hover:text-gray-700">Home</Link>
          {" · "}
          <Link href="/terms" className="hover:text-gray-700">Terms</Link>
          {" · "}
          <Link href="/privacy" className="hover:text-gray-700">Privacy</Link>
        </div>
      </footer>
    </div>
  );
}
